version: "3.9"
services:
  mmseq2:
    build:
      context: ../..
      dockerfile: ./ops/docker/Dockerfile.mmseq2
    ports:
      - 8080:8080
    environment:
      PG_HOST: localhost
      PG_PORT: 5432
      PG_DATABASE: bioseqdb
      PG_USER: postgres
      PG_PASSWORD: password
    command: ["sleep","infinity"]
    networks:
      - development

  postgres:
    depends_on:
      - mmseq2
    build:
      context: ../..
      dockerfile: ./ops/docker/Dockerfile.pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bioseqdb
      PGDATA: /pgtmpfs
    tmpfs:
      - /pgtmpfs
    networks:
      - development


networks:
  development:
    name: development